MODEL:
  TYPE: vit
  NAME: timm_vit
  DROP_PATH_RATE: 0.1
  NUM_CLASSES: 1000
  VIT:
    # Preferred: specify a timm model id and arbitrary kwargs in MODEL_ARGS
    MODEL: vit_base_patch16_224
    MODEL_ARGS:
      img_size: 224
      in_chans: 3
      patch_size: 16
      embed_dim: 768
      depth: 12
      num_heads: 12
      mlp_ratio: 4.0
      qkv_bias: true
      drop_rate: 0.0
      drop_path_rate: 0.1
  
DATA:
  IMG_SIZE: 224

PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: timm_vit__vit_base_patch16_224

